In [2]:
import numpy as np

array = np.array([[1,2,3],
               [4,5,6]]) 
print(array.ndim) #矩阵的维度
print(array.shape)#大小n*m
print(array.size) #  有多少个元素


2
(2, 3)
6


In [4]:
a = np.array([],dtype=np.int64)
print(a.dtype)
#(默认)

a = np.array([],dtype=np.int32)
print(a.dtype)

int64
int32


In [7]:
a = np.zeros( (3,4) )  
print(a)

a = np.ones( (3,4) )     
print(a)

a = np.empty( (3,4) )    
print(a)

a = np.arange(10,20,2) #start,end,step  (末尾取不到)
print(a)

a = np.arange(12).reshape((3,4))  #(末尾取不到)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
a = np.linspace(1,10,5) #生成从1到10的5条线段
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
c = a -/+ b
c = b**4 4次方
c = np.sin(a)/cos/tan
